events {
    worker_connections 1024;
}

http {
    server {

        listen 80;
        server_name localhost;

        location /api/auth/authenticate {
            internal;
            proxy_pass_request_body off;
            proxy_set_header Content-Length "";
            proxy_set_header X-Original-URI $request_uri;

            proxy_pass http://auth-service:3000/auth/validate;
        }

        location /api/auth/login {
            proxy_pass http://auth-service:3000/auth/login;
        }

        location /api/auth/register {
            proxy_pass http://auth-service:3000/auth/register;
        }

        location /api/health {
            ##auth_request /api/auth/authenticate;
            proxy_pass http://auth-service:3000/api/health;
        }
    }
}