export const currentUser = {
  name: "EnzoDu77",
  tag: "enzo_du_78",
  subscriptions: 584,
  subscribers: 975_430,
  posts: 1_420_023,
  profile: "https://i.pravatar.cc/100?img=12",
};

export const posts = [
  {
    id: 1,
    username: "Camille Delcourt",
    tag: "camilleds",
    timeAgo: "48 min",
    timeLeft: "2 h 14",
    minutesLeft: 134,
    totalMinutes: 720,
    profile: "https://i.pravatar.cc/100?img=44",
    content: "Balade improvisée ce matin. Parfois les meilleurs plans n'étaient pas prévus.",
    image: "https://picsum.photos/seed/mountain1/700/350",
    likes: 42,
    comments: 8,
    reposts: 5,
  },
  {
    id: 2,
    username: "Lucas Martin",
    tag: "lucasmartin",
    timeAgo: "1 h",
    timeLeft: "1 h 03",
    minutesLeft: 63,
    totalMinutes: 720,
    profile: "https://i.pravatar.cc/100?img=33",
    content: "Nouvel article sur mon blog : 5 livres qui m'ont inspiré cet été.",
    link: {
      title: "5 livres pour ralentir et mieux créer",
      description: "Quelques lectures qui font du bien et ouvrent l'esprit.",
      url: "lucasmartin.com",
      image: "https://picsum.photos/seed/books1/200/130",
    },
    likes: 29,
    comments: 6,
    reposts: 3,
  },
  {
    id: 3,
    username: "Inès Leroy",
    tag: "ines_l",
    timeAgo: "2 h",
    timeLeft: "45 min",
    minutesLeft: 45,
    totalMinutes: 180,
    profile: "https://i.pravatar.cc/100?img=47",
    content: "Petite pensée du jour. Le vent ne force rien, et pourtant tout change.",
    likes: 18,
    comments: 2,
    reposts: 0,
  },
];

export const dansLAirItems = [
  {
    id: 1,
    username: "Camille",
    subtitle: "Montagne",
    timeLeft: "47 min",
    profile: "https://i.pravatar.cc/100?img=44",
    image: "https://picsum.photos/seed/mountain1/250/350",
  },
  {
    id: 2,
    username: "Lucas",
    subtitle: "Carnet",
    timeLeft: "1 h 12",
    profile: "https://i.pravatar.cc/100?img=33",
    image: "https://picsum.photos/seed/coffee1/250/350",
  },
  {
    id: 3,
    username: "Inès",
    subtitle: "Croquis du jour",
    timeLeft: "2 h 03",
    profile: "https://i.pravatar.cc/100?img=47",
    image: "https://picsum.photos/seed/sketch1/250/350",
  },
  {
    id: 4,
    username: "Studio",
    subtitle: "vibes",
    timeLeft: "35 min",
    profile: "https://i.pravatar.cc/100?img=55",
    image: "https://picsum.photos/seed/music1/250/350",
  },
  {
    id: 5,
    username: "Chloé",
    subtitle: "Ciel du soir",
    timeLeft: "1 h 45",
    profile: "https://i.pravatar.cc/100?img=23",
    image: "https://picsum.photos/seed/sunset1/250/350",
  },
];

export const expiringPosts = [
  {
    id: 1,
    name: "Jeanne R.",
    content: "Dernier café du lundi",
    timeLeft: "22 min",
    progress: 0.08,
    profile: "https://i.pravatar.cc/100?img=5",
    thumbnail: "https://picsum.photos/seed/coffee2/80/80",
  },
  {
    id: 2,
    name: "Alexandre B.",
    content: "Work in progress",
    timeLeft: "37 min",
    progress: 0.12,
    profile: "https://i.pravatar.cc/100?img=8",
    thumbnail: "https://picsum.photos/seed/work1/80/80",
  },
  {
    id: 3,
    name: "Marie P.",
    content: "Coucher de soleil",
    timeLeft: "48 min",
    progress: 0.18,
    profile: "https://i.pravatar.cc/100?img=27",
    thumbnail: "https://picsum.photos/seed/sunset3/80/80",
  },
];

export const suggestions = [
  {
    id: 1,
    name: "Clara Moreau",
    tag: "claramoreau",
    profile: "https://i.pravatar.cc/100?img=49",
  },
  {
    id: 2,
    name: "Paul Vasseur",
    tag: "paul.vrs",
    profile: "https://i.pravatar.cc/100?img=59",
  },
  {
    id: 3,
    name: "Léa Bernard",
    tag: "leabrd_",
    profile: "https://i.pravatar.cc/100?img=36",
  },
];